# Generated by Django 5.0.6 on 2025-04-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('trainer', 'Trainer')], default='user', max_length=10),
        ),
    ]
