# Generated by Django 5.0.6 on 2025-04-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diet_recipe_ingredient_recipestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='workout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='api.workout'),
        ),
    ]
