# Generated by Django 5.0.6 on 2025-04-10 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workoutsession_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='carb_limit',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='daily_calorie_deficit',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='protein_intake',
        ),
        migrations.AlterField(
            model_name='diet',
            name='benefits',
            field=models.TextField(blank=True, default='No benefits specified.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diet',
            name='carb_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fat_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diet',
            name='protein_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField()),
                ('foods', models.TextField()),
                ('avoid', models.TextField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='api.diet')),
            ],
        ),
    ]
