# Generated by Django 5.0.6 on 2025-05-18 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workoutplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(related_name='template_plans', to='api.exercise')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
