# Generated by Django 5.0.6 on 2025-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_diet_carb_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
