# Generated by Django 5.0.6 on 2025-04-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diet_images/'),
        ),
    ]
