# Generated by Django 5.0.6 on 2025-04-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_diet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.diettype'),
        ),
    ]
