# Generated by Django 5.0.6 on 2025-04-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workout_summary_alter_recipe_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout', to='api.workoutsession'),
        ),
    ]
