# Generated by Django 5.0.6 on 2025-04-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_workoutsession_workout_workout_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_session', to='api.workoutsession'),
        ),
    ]
