# Generated by Django 5.0.6 on 2025-03-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='personal_best',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workout',
            name='progress_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='progress_pics/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='rest_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='api.exercise'),
        ),
    ]
