# Generated by Django 5.0.6 on 2025-03-20 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_calories_burned_workout_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttracking',
            old_name='duration',
            new_name='rest_time',
        ),
        migrations.RemoveField(
            model_name='workouttracking',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='workouttracking',
            name='reps',
        ),
        migrations.AddField(
            model_name='workouttracking',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='workouttracking',
            name='sets',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='workouttracking',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.workout'),
        ),
    ]
