# Generated by Django 5.0.6 on 2025-03-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_duration_workouttracking_rest_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workout_images/')),
                ('workout_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.workouttracking')),
            ],
        ),
    ]
