# Generated by Django 5.0.6 on 2025-03-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workoutimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutImage',
        ),
    ]
